In [2]:
import numpy as np

In [3]:
A = np.array([[4, 2, 0], [1, 3, 2], [-1, 3, 10]])
print (A)

[[ 4  2  0]
 [ 1  3  2]
 [-1  3 10]]


In [4]:
A[[0, 1], :] = A[[1, 0], :]
print(A)

[[ 1  3  2]
 [ 4  2  0]
 [-1  3 10]]


In [5]:
A[1]= A[1]+(-4)*A[0]
A[2] = A[2] + A[0]
print(A)

[[  1   3   2]
 [  0 -10  -8]
 [  0   6  12]]


In [6]:
A[1]= A[1]/(-2)
A[2] = A[2]/6
print(A)

[[1 3 2]
 [0 5 4]
 [0 1 2]]


In [7]:
A[[1, 2], :]=A[[2, 1], :]
print(A)

[[1 3 2]
 [0 1 2]
 [0 5 4]]


In [8]:
A[2]=A[2]+(-5)*A[1]
print(A)

[[ 1  3  2]
 [ 0  1  2]
 [ 0  0 -6]]
