In [10]:
import sklearn
from sklearn.datasets import load_iris
import numpy as np

In [65]:
X, y = load_iris(return_X_y=True)
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### Статистичний метод VarianceThreshold

In [14]:
from sklearn.feature_selection import VarianceThreshold

In [15]:
select = VarianceThreshold(threshold=0.4)

In [27]:
X_new = select.fit_transform(X)
X_new [:5]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2]])

### Статистичний метод SelectKBest

In [19]:
from sklearn.feature_selection import SelectKBest, f_classif

In [20]:
X.shape

(150, 4)

In [28]:
X_kbest = SelectKBest(f_classif, k = 2).fit_transform(X,y)
X_kbest[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

### Відбір ознак на основі ваг у моделі за допомогою методу SelectFromModel

In [37]:
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns

In [40]:
model = SelectFromModel(estimator= DecisionTreeClassifier(), threshold=0.2)

In [41]:
model.fit(X, y)

SelectFromModel(estimator=DecisionTreeClassifier(), threshold=0.2)

In [51]:
X_sfm = X[:,model.get_support()]
X_sfm[:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

### Метод головних компонентів PCA

In [52]:
from sklearn.decomposition import PCA

In [53]:
pca = PCA(n_components=2)

In [55]:
X_pca = pca.fit_transform(X)
X_pca[:5]

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451]])

 ### Сингулярне розкладання матриць (SVD)

In [56]:
from sklearn.decomposition import TruncatedSVD

In [57]:
svd  =TruncatedSVD(n_components=2)

In [59]:
X_svd = svd.fit_transform(X)
X_svd[:5]

array([[5.91274714, 2.30203322],
       [5.57248242, 1.97182599],
       [5.44697714, 2.09520636],
       [5.43645948, 1.87038151],
       [5.87564494, 2.32829018]])

### Лінійний дискриміннантний аналіз (LDA) 

In [60]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [61]:
lda = LinearDiscriminantAnalysis()

In [64]:
X_lda = lda.fit_transform(X, y)
X_lda[:5]

array([[ 8.06179978, -0.30042062],
       [ 7.12868772,  0.78666043],
       [ 7.48982797,  0.26538449],
       [ 6.81320057,  0.67063107],
       [ 8.13230933, -0.51446253]])